// Renders the profile's SVG slices and README.md from data/. Output depends
// only on data/, the fonts, and this code, so unchanged data produces
// byte-identical files.
//
// The console design, contribution city, and slice technique are ported from
// Giorgi Kobaidze's render.py (github.com/georgekobaidze/georgekobaidze, MIT;
// see NOTICE). Every image has a phone variant in assets/phone/ that GitHub
// swaps in through <picture> below 600px.
//
//   node src/render.ts [--theme neon|amber] [--root <dir>]
import {mkdir, readFile, rm, writeFile} from 'node:fs/promises';
import {parseArgs} from 'node:util';
import {THEMES, type Theme, esc} from './console.ts';
import {type Calendar, type Installs, type Project, type Snapshot, type Stars, slugify} from './data.ts';
import {beyondMise, phoneBeyondMise} from './sections/beyond.ts';
import {city, cityAlt, phoneCity} from './sections/city.ts';
import {LINKS, button, footer, header, headerAlt, phoneButton, phoneFooter, phoneHeader, phoneSectionHead, sectionHead} from './sections/frame.ts';
import {installs, phoneInstalls} from './sections/installs.ts';
import {articleRow, card, logoHref, phoneArticleRow, phoneCard, phoneWritingMore, writingMore} from './sections/projects.ts';
import {phoneStats, stats} from './sections/stats.ts';
import {phoneTrendingHead, phoneTrendingLegend, phoneTrendingRow, trendingHead, trendingLegend, trendingRow, trends} from './sections/trending.ts';
import {CREDIT_POST, CREDIT_URL} from './shared.ts';

const DEFAULT_THEME = 'neon';
const CARDS = 8;
// <source srcset> is not rewritten like a relative <img src>, so it is absolute.
const RAW = 'https://github.com/jdx/jdx/raw/main/assets';
const PHONE_QUERY = '(max-width: 600px)';

// The page is built as rows of images; each add() writes a desktop and a
// phone SVG and appends a <picture> to the current row. Images in a row sit
// side by side with no whitespace between them so their widths sum to 100%.
class Page {
	files = new Map<string, string>();
	rows: string[][] = [];

	add(file: string, [desktop, phone]: [string, string], width: string, alt: string, href?: string, sameRow = false): void {
		this.files.set(file, desktop);
		this.files.set(`phone/${file}`, phone);
		const img = `<picture><source media="${PHONE_QUERY}" srcset="${RAW}/phone/${file}"><img src="./assets/${file}" width="${width}" align="top" alt="${esc(alt)}"></picture>`;
		const html = href ? `<a href="${esc(href)}">${img}</a>` : img;
		if (sameRow && this.rows.length) this.rows.at(-1)!.push(html);
		else this.rows.push([html]);
	}

	readme(): string {
		return `<!-- Generated by \`mise run readme\` from src/. Edit that, not this. -->
<p align="center">
${this.rows.map(r => r.join('')).join('\n')}
</p>

<p align="center"><sub>Regenerated daily by <code>mise run readme</code> (<a href="https://github.com/jdx/jdx">source</a>). Console design and contribution city by <a href="${CREDIT_URL}">Giorgi Kobaidze</a> (<a href="${CREDIT_POST}">how he built it</a>), used under MIT.</sub></p>
`;
	}
}

async function main() {
	const {values} = parseArgs({options: {theme: {type: 'string', default: DEFAULT_THEME}, root: {type: 'string', default: '.'}}});
	const t = THEMES[values.theme!];
	if (!t) throw new Error(`unknown theme ${values.theme}`);
	const root = values.root!;

	const s: Snapshot = JSON.parse(await readFile('data/snapshot.json', 'utf8'));
	const history: Record<string, number> = JSON.parse(await readFile('data/mau.json', 'utf8').catch(() => '{}'));
	const calendar: Calendar | null = JSON.parse(await readFile('data/calendar.json', 'utf8').catch(() => 'null'));
	const starData: Stars | null = JSON.parse(await readFile('data/stars.json', 'utf8').catch(() => 'null'));
	const installData: Installs | null = JSON.parse(await readFile('data/installs.json', 'utf8').catch(() => 'null'));
	const updated = calendar?.at(-1)?.[0] ?? s.mau?.date ?? '';
	const carded = s.projects.slice(0, CARDS);
	const rest = s.projects.slice(CARDS);
	let n = 0;
	const counter = () => `// ${String(++n).padStart(2, '0')}`;
	const both = (a: Promise<string>, b: Promise<string>) => Promise.all([a, b]);
	const head = (name: string, cmd: string, comment = '') => {
		const c = counter();
		return both(sectionHead(t, name, c, cmd, comment), phoneSectionHead(t, name, c, cmd, comment));
	};

	const page = new Page();
	page.add('header.svg', await both(header(t, s), phoneHeader(t, s)), '100%', headerAlt(s));
	page.add('links.svg', await head('links', 'ping jdx --all-channels'), '100%', 'Links');
	for (const [k, b] of LINKS.entries()) {
		page.add(`links/${k + 1}.svg`, await both(button(t, b, k, LINKS.length), phoneButton(t, b, k, LINKS.length)), '20%', b.label, b.url, k > 0);
	}

	if (starData) {
		const {rows, days} = trends(t, starData, s.projects);
		if (rows.length >= 3) {
			const c = counter();
			page.add('trending.svg', await both(trendingHead(t, starData, days, c), phoneTrendingHead(t, starData, days, c)), '100%',
				`Trending: stars gained by jdx's tools in the ${days} days to ${starData.end}`);
			for (const [i, r] of rows.entries()) {
				page.add(`trending/${i + 1}.svg`, await both(trendingRow(t, r, i, rows[0].gain), phoneTrendingRow(t, r, i, rows[0].gain)), '100%',
					`${r.p.name}: +${r.gain} stars in ${days} days${r.isNew ? ' (new)' : ''}, ${r.total} total`, r.p.href);
			}
			page.add('trending/legend.svg', await both(trendingLegend(t), phoneTrendingLegend(t)), '100%', 'Legend');
		}
	}
	{
		const c = counter();
		page.add('stats.svg', await both(stats(t, s, history, updated, c), phoneStats(t, s, history, updated, c)), '100%', 'Stats');
	}
	if (calendar) {
		const c = counter();
		page.add('contribution-city.svg', await both(city(t, calendar, updated, c), phoneCity(t, calendar, updated, c)), '100%', cityAlt(calendar));
	}
	if (starData) {
		const c = counter();
		page.add('beyond-mise.svg', await both(beyondMise(t, starData, s.projects, c), phoneBeyondMise(t, starData, s.projects, c)), '100%',
			'Beyond mise: cumulative stars of every other tool');
	}
	if (installData) {
		const c = `// ${String(n + 1).padStart(2, '0')}`;
		const svg = await installs(t, installData, starData, s.projects, c);
		const phone = await phoneInstalls(t, installData, starData, s.projects, c);
		if (svg && phone) {
			n++;
			page.add('installs.svg', [svg, phone], '100%', 'Installs of jdx tools through mise');
		}
	}

	page.add('projects.svg', await head('projects', 'ls -l ~/projects'), '100%', 'Projects');
	for (const [i, p] of carded.entries()) {
		const side = i % 2 === 0 ? 'L' : 'R';
		page.add(`projects/${slugify(p.name)}.svg`, await both(card(t, p, side, 0.3 + i * 0.12), phoneCard(t, p, side, 0.3 + i * 0.12)), '50%',
			`${p.name}: ${p.description} Install: ${p.install}`, p.href, i % 2 === 1);
	}
	for (const [k, p] of rest.entries()) {
		const logo = await logoHref(p);
		const icon = (_t: Theme, x: number, y: number) => (logo ? `<image href="${logo}" x="${x}" y="${y}" width="18" height="18"/>` : '');
		const b = {label: p.name, handle: p.tagline || p.kind, url: p.href, icon};
		page.add(`projects/also-${slugify(p.name)}.svg`, await both(button(t, b, k, rest.length, 0.3), phoneButton(t, b, k, rest.length, 0.3)),
			`${100 / rest.length}%`, `${p.name}: ${p.description}`, p.href, k > 0);
	}
	if (s.posts.length) {
		page.add('writing.svg', await head('writing', 'tail -n 5 ~/jdx.dev/posts.log', '# auto-updated'), '100%', 'Writing: latest posts on jdx.dev');
		for (const [i, p] of s.posts.entries()) {
			page.add(`writing/post-${i + 1}.svg`, await both(articleRow(t, p, i), phoneArticleRow(t, p, i)), '100%',
				`${p.title}, published ${p.date}, ${p.reading_time} min read`, p.url);
		}
		page.add('writing/all-posts.svg', await both(writingMore(t), phoneWritingMore(t)), '100%', 'Read all posts on jdx.dev', 'https://jdx.dev/posts/');
	}
	page.add('footer.svg', await both(footer(t), phoneFooter(t)), '100%', 'Connection closed.');

	await rm(`${root}/assets`, {recursive: true, force: true});
	for (const [name, content] of page.files) {
		const path = `${root}/assets/${name}`;
		await mkdir(path.slice(0, path.lastIndexOf('/')), {recursive: true});
		await writeFile(path, content);
	}
	await writeFile(`${root}/README.md`, page.readme());
	console.log(`rendered ${page.files.size} SVGs (${t.name}) and README.md into ${root}`);
}

await main();
